<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\WakeGuard.Contracts\WakeGuard.Contracts.csproj" />
    <ProjectReference Include="..\WakeGuard.Core\WakeGuard.Core.csproj" />
  </ItemGroup>
</Project>
